# Automatically generated by HonestCode
# Do not edit this file as it will be overwritten

Feature: Dashboard
    As a user
  I want to see a dashboard with information about my accounts

  Background: Dashboard screen
    Given the user is logged on dashboard screen
    When user is on the "dashboard" screen

  Scenario: Movements list
    Then he should see a list with the banking movements

  Scenario: Prizes lists
    When the user navigate to the prizes section
    Then he should see lists of his friends and global prizes

  Scenario: Accounts lists
    When the user navigate to the accounts section
    Then he should see lists of accounts and expenses and operations

  Scenario: Position balance
    Then he should see the total balance of all the accounts
    And he should see the total balance in prizes

  Scenario: Winners lists
    When the user navigate to the winners section
    Then he should see lists of his friends and recents winners
