# Automatically generated by HonestCode
# Do not edit this file as it will be overwritten

Feature: Login for personal use
    as an user
  I want to login into the TikTakPay system

  Background: Base user login
    Given user is on the "login" screen

@valid
  Scenario Outline: Login successful
    When the user enters a valid "<identificationId>" and "<password>" on login form
    Then user logged successful

    Examples:
      | identificationId     | password |
      | 616666666            | aa123456 |
      | prueba@tiktakpay.com | bb123456 |

@valid
  Scenario: Logout
    Given User is logged
    When User log out
    Then Application show us a confirm message
    And User press the ok button
    And Application shows login screen

@valid
  Scenario Outline: Login fail
    When the user enters an invalid "<identificationId>" and "<password>" on login form
    Then invalid login message is displayed

    Examples:
      | identificationId      | password |
      | 666000000             | aa654312 |
      | prueba3@tiktakpay.com | bb123456 |
