# Automatically generated by HonestCode
# Do not edit this file as it will be overwritten

Feature: Operation PIN
    As a customer
  I want to manage my operation PIN

  Background: Operation PIN screen
    Given the user is logged on application

@valid @PIN
  Scenario: Operation PIN creation
    Given user is on the "create pin form" screen
    When He enters the PIN "1234" in the "pin field"
    And He enters the PIN "1234" in the "repeat pin field"
    Then The PIN is established successful

@invalid @PIN
  Scenario: Invalid Operation PIN updated with wrong repeated PIN
    Given user is on the "change pin form" screen
    When He enters a valid password in the "password field"
    And He enters the PIN "1234" in the "pin field"
    And He enters the PIN "1111" in the "repeat pin field"
    Then the next button on update PIN screen is disabled

@invalid @PIN
  Scenario: Invalid operation PIN update with wrong password
    Given user is on the "change pin form" screen
    When He enters a invalid password in the "password field"
    Then The fail message appears

@valid @PIN
  Scenario: Operation PIN update
    Given user is on the "change pin form" screen
    When He enters a valid password in the "password field"
    And He enters the PIN "0000" in the "pin field"
    And He enters the PIN "0000" in the "repeat pin field"
    Then The PIN has changed successful

@invalid @PIN
  Scenario: Invalid Operation PIN creation with wrong repeated PIN
    Given user is on the "create pin form" screen
    When He enters the PIN "1234" in the "pin field"
    And He enters the PIN "1111" in the "repeat pin field"
    Then the next button on PIN screen is disabled
